# Generated by Django 3.1.7 on 2021-08-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'نمونه کار ها'},
        ),
        migrations.AddField(
            model_name='work',
            name='work_url',
            field=models.URLField(default='aparat.com', verbose_name='کد نمونه کار در آپارات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_job',
            field=models.CharField(max_length=150, verbose_name='وظیفه در تیم'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='memeber_name',
            field=models.CharField(max_length=100, verbose_name='نام عضو تیم'),
        ),
    ]
