# Generated by Django 3.1.7 on 2021-08-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210818_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='corp_name',
            field=models.CharField(default='default', max_length=100, verbose_name='نام سازمان'),
            preserve_default=False,
        ),
    ]
