# Generated by Django 3.1.7 on 2021-08-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_corporation_corp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='member_image',
            field=models.ImageField(null='True', upload_to='', verbose_name='تصویر عضو'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='corporation',
            name='corp_image',
            field=models.ImageField(null='True', upload_to='', verbose_name='لوگوی سازمان'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='corp_name',
            field=models.CharField(max_length=100, null='True', verbose_name='نام سازمان'),
        ),
    ]
