# Generated by Django 3.1.7 on 2021-08-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210818_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='memeber_name',
            new_name='member_name',
        ),
    ]
