# Generated by Django 3.1.7 on 2021-08-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210818_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporation',
            options={'verbose_name_plural': 'همکاری ها'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name_plural': 'اعضای تیم'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name_plural': 'نمونه کار ها'},
        ),
        migrations.AlterField(
            model_name='corporation',
            name='corp_image',
            field=models.ImageField(null='True', upload_to='corp/', verbose_name='لوگوی سازمان'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_image',
            field=models.ImageField(null='True', upload_to='team/', verbose_name='تصویر عضو'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_description',
            field=models.TextField(max_length=200, null=True, verbose_name='توضیح کوتاه در مورد نمونه کار'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_url',
            field=models.CharField(max_length=300, verbose_name='کد نمونه کار در آپارات'),
        ),
    ]
